//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockXChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAverageCost
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string Side { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Volume { get; set; }
        public int ClientAverageCostID { get; set; }
        public Nullable<double> Gross { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<double> Vat12 { get; set; }
        public Nullable<double> SalesTax { get; set; }
        public Nullable<double> PCD_SCCP { get; set; }
        public Nullable<double> BuyPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<double> NetPrice { get; set; }
        public Nullable<double> SumNetPrice { get; set; }
        public Nullable<double> NetVolume { get; set; }
        public Nullable<double> AverageCost { get; set; }
    }
}
